language: python
python:
  - "2.7"
before_script:
  - mysql -e 'create database oneanddone character set utf8;'
  - cp oneanddone/settings/local.py-travis oneanddone/settings/local.py
before_install:
  - git submodule update --init --recursive
install: pip install -r requirements/dev.txt
script: python manage.py test
